# use UTF-8 everywhere
export LANG=en_US.UTF-8

# specify location of kshrc
export ENV=$HOME/.kshrc

export PATH HOME TERM
export ENV=$HOME/.kshrc
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.yarn/bin
export PATH=$PATH:$HOME/.npm-packages

NPM_PACKAGES=$HOME/.npm-packages
NODE_PATH="$NPM_PACKAGES/lib/modules:$NODE_PATH"
export PATH=$NPM_PACKAGES/bin:$PATH

# load Xresources file
xrdb -merge $HOME/.Xresources &

# xautolock will lock your display after a period of inactivity
# xautolock -time 1 -locker "/usr/local/bin/xflock4" &

# xidle will suspend the machine after a period of inactivity
# xidle -timeout 85  -program "/usr/sbin/apm -z" &
# xidle -program "/usr/local/bin/xflock4" -timeout 500 &

# disable system beep
xset b off &

# if you have a ThinkPad, the following lines enable TrackPoint
# scrolling by dragging with the middle button.
#xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1 
#xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2 
#xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5 

# use caps lock as ctrl key
#setxkbmap -option ctrl:nocaps

#xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1 &
#xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5 &
#xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2 &
#xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Timeout" 50 &
#xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Inertia" 3 &
#xinput set-prop "/dev/wsmouse" "Device Accel Constant Deceleration" 0 &

# set your background color
xsetroot -solid gray40 &
# /home/psi/Downloads/lemonbar.sh | lemonbar -g 1366x15 -b -n "lemonbar" -f $lbfont &

exec pkill xconsole &
exec ck-launch-session startxfce4
# exec ck-launch-session cwm
# exec i3
