#!/bin/sh
# control cmus-remote(1) with any ssh client. This is actually an 
# alias to avoid typing long commands in the shell.
# synonymous to: `cmus-remote --server [server socket] arg1 arg2 arg3(optional)`

cmus-remote --server $XDG_RUNTIME_DIR/cmus-socket "$1" "$2" "$3?"
