#!/bin/sh
#
# Copyright (c) 2020: psi <cy.lonsido@gmail.com>
# OS: OpenBSD amd64
# Session: xfce4-session
# WM: i3
#
# This script is for toggling audio muting on top of
# the sndio(7) interface.
#
# Current volume is saved to a file (".currentvol")
# in user's $HOME. It is then retrieved later when
# the audio is toggled back.


IF_MUTED="$(sndioctl -n output.mute)"

gdbus call --session\
          --session \
          --dest org.freedesktop.Notifications \
          --object-path /org/freedesktop/Notifications \
          --method org.freedesktop.Notifications.CloseNotification \
          "$(cat /tmp/notify_id)"

if [ "$IF_MUTED" -eq 0 ];then
  MESSAGE="Sound has been restored"
  ICON="audio-volume-high"
else
  MESSAGE="Your sound is now muted"
  ICON="audio-volume-muted"
fi

gdbus call --session \
            --dest org.freedesktop.Notifications \
            --object-path /org/freedesktop/Notifications \
            --method org.freedesktop.Notifications.Notify \
              my_app_name \
              42 \
              "$ICON" \
              "sndio" \
              "$MESSAGE" \
              [] \
              {} \
              30 | awk '{printf("%d", $2)}' | cat > /tmp/notify_id
