#!/bin/sh
#
# Copyright (c) 2020: psi <cy.lonsido@gmail.com>
# OS: OpenBSD amd64
# Session: xfce4-session
# WM: i3
#
# This script is for toggling audio muting on top of
# the sndio(7) interface.
#
# Current volume is saved to a file (".currentvol")
# in user's $HOME. It is then retrieved later when
# the audio is toggled back.


IF_MUTED="$(sndioctl -n output.mute)"


if [ "$IF_MUTED" -eq 0 ];then
  notify-send "sndio" "Sound has been restored"
else
  notify-send "sndio" "Your sound is now muted"
fi
