#!/bin/sh
#
# Copyright (c) 2017-2020: psi <cy.lonsido@gmail.com>
# OS: OpenBSD amd64
# Session: xfce4-session
# WM: i3
# 
# This script makes use of trash-cli by andreafrancia/trash-cli,
# a freedesktop.org compliant command line interface.
# Repo: https://github.com/andreafrancia/trash-cli.git 
#
# Requirements: 
#   -trash-cli (andreafrancia/trash-cli)
#   -xfce4-notifyd
#   -zenity (dialog)



ZEN_TITLE="Empty Trash Request"
ZEN_TEXT="All items in trash will be permanently deleted." 
ZEN_TEXT="${ZEN_TEXT}\\n"
ZEN_TEXT="${ZEN_TEXT} Do you want to proceed?"

NOTIFY_SUCCESS_TITLE="Success"
NOTIFY_SUCCESS_MESSAGE="Trash is now empty"
NOTIFY_NO_ACTION_TITLE="No Action Needed"
NOTIFY_NO_ACTION_MESSAGE="Trash is already empty"

TRASH_LIST="$(trash-list | wc -c)"

ARGS=$?

# Checks to see whether trash contains files then
if [ "$TRASH_LIST" -ne 0 ];then

  # asks the user to confirm an empty request.
  zenity --question \
    --title="$ZEN_TITLE" \
    --text="$ZEN_TEXT" \
    --ok-label="Confirm" \
    --cancel-label="Cancel" \
    --no-wrap \
    --width=200 \
    --height=80

  # if ok/confirm
  if [ "$ARGS" -eq 0 ];then
    trash-empty
    # notify-send [title] [message] [options]
    notify-send "$NOTIFY_SUCCESS_TITLE" "$NOTIFY_SUCCESS_MESSAGE" -i emblem-ok 
  fi

# no need to clear empty trash
else
  notify-send "$NOTIFY_NO_ACTION_TITLE" "$NOTIFY_NO_ACTION_MESSAGE" -i xfce-trash_empty
fi
